usecase-beta

    actor Administrateur
    actor Auteur
    actor Visiteur

    UC1("Consulter les catégories")
    UC2("Ajouter une catégorie")
    UC3("Modifier une catégorie")
    UC4("Supprimer une catégorie")
    UC5("Créer un auteur")
    UC6("Valider un article")
    UC7("Publier un article")
    
    UC8("Ajouter un article")
    UC12("Modifier un article (non publié)")
    UC13("Supprimer un article (non publié)")
    UC9("Changer son profil")
    UC10("Réinitialiser mot de passe")
    
    UC11("Consulter les articles")

    Administrateur --> UC1
    Administrateur --> UC2
    Administrateur --> UC3
    Administrateur --> UC4
    Administrateur --> UC5
    Administrateur --> UC6
    Administrateur --> UC7
    
    Auteur --> UC8
    Auteur --> UC12
    Auteur --> UC13
    Auteur --> UC9
    Auteur --> UC10
    
    Visiteur --> UC11
